require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 3.1.2
  TargetRailsVersion: 7.0.5
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'
    - 'bin/**/*'
    - 'spec/rails_helper.rb'
Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 23
Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*
Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
